# Generated by Django 4.2.7 on 2025-10-07 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coin_decimal_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('trade_quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('trade_price_per_coin', models.DecimalField(decimal_places=50, max_digits=1000)),
                ('balance_before_trade', models.DecimalField(decimal_places=50, max_digits=1000)),
                ('balance_after_trade', models.DecimalField(decimal_places=50, max_digits=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_histories', to='api.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trade_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=50, default=500000.0, max_digits=1000)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_balance',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='api.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet',
                'unique_together': {('user', 'coin')},
            },
        ),
    ]
