name: Deploy Backend to AWS

on:
  push:
    branches: [main]
    paths: ['crypto_backend/**']
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: crypto_backend
      run: |
        # Run basic syntax and import checks
        python -m py_compile crypto_backend/settings.py
        python -m py_compile crypto_backend/urls.py
        python -m py_compile api/models.py
        python -m py_compile api/views.py
        echo "✅ Python syntax checks passed"
        
        # Try to run Django checks
        python manage.py check --settings=crypto_backend.test_settings
        echo "✅ Django system checks passed"
        
        # Run a simple test to verify Django setup
        python -c "
        import os
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'crypto_backend.test_settings')
        import django
        django.setup()
        from django.contrib.auth.models import User
        print('✅ Django setup successful')
        "

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Install EB CLI
      run: |
        pip install awsebcli


    - name: Deploy to Elastic Beanstalk
      working-directory: crypto_backend
      run: |
        # Use existing application without eb init
        export AWS_DEFAULT_REGION=ap-northeast-1
        
        # Create complete EB config
        mkdir -p .elasticbeanstalk
        cat > .elasticbeanstalk/config.yml << EOF
        branch-defaults:
          main:
            environment: ${{ secrets.EB_ENVIRONMENT_NAME }}
        global:
          application_name: crypto-tracker-api
          default_ec2_keyname: null
          default_platform: python-3.11
          default_region: ap-northeast-1
          include_git_submodules: true
          instance_profile: null
          platform_name: null
          platform_version: null
          profile: null
          sc: git
          workspace_type: Application
        EOF
        
        # Verify EB configuration
        echo "EB Config created successfully"
        echo "Deploying to: ${{ secrets.EB_ENVIRONMENT_NAME }}"
        
        # Deploy to existing environment
        echo "Deploying to environment: ${{ secrets.EB_ENVIRONMENT_NAME }}"
        eb deploy ${{ secrets.EB_ENVIRONMENT_NAME }}