name: Deploy Backend to AWS

on:
  push:
    branches: [main]
    paths: ['crypto_backend/**']
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Temporarily skip tests to focus on deployment
    # - name: Run tests
    #   working-directory: crypto_backend
    #   run: |
    #     python manage.py test --settings=crypto_backend.test_settings

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Install EB CLI
      run: |
        pip install awsebcli


    - name: Deploy to Elastic Beanstalk
      working-directory: crypto_backend
      run: |
        # Initialize EB if not already initialized
        if [ ! -f .elasticbeanstalk/config.yml ]; then
          echo "Initializing EB application..."
          eb init crypto-tracker-api --region ap-northeast-1 --platform python-3.11
        fi
        
        # Deploy to existing environment
        echo "Deploying to environment..."
        eb deploy ${{ secrets.EB_ENVIRONMENT_NAME }}